<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <MacTargetFramework>net8.0</MacTargetFramework>
    <WindowsTargetFramework>net10.0</WindowsTargetFramework>
    <BuildTargetPlatform Condition="'$(BuildTargetPlatform)' == '' and ('$(RuntimeIdentifier)' == 'osx-arm64' or '$(RuntimeIdentifier)' == 'osx-x64')">macos</BuildTargetPlatform>
    <BuildTargetPlatform Condition="'$(BuildTargetPlatform)' == '' and ('$(RuntimeIdentifier)' == 'win-x64' or '$(RuntimeIdentifier)' == 'win-arm64')">windows</BuildTargetPlatform>
    <BuildTargetPlatform Condition="'$(BuildTargetPlatform)' == '' and '$(TargetFramework)' == '$(MacTargetFramework)'">macos</BuildTargetPlatform>
    <BuildTargetPlatform Condition="'$(BuildTargetPlatform)' == '' and '$(TargetFramework)' == '$(WindowsTargetFramework)'">windows</BuildTargetPlatform>
    <BuildTargetPlatform Condition="'$(BuildTargetPlatform)' == '' and '$([MSBuild]::IsOSPlatform(`OSX`))' == 'true'">macos</BuildTargetPlatform>
    <BuildTargetPlatform Condition="'$(BuildTargetPlatform)' == ''">windows</BuildTargetPlatform>
  </PropertyGroup>

  <PropertyGroup Condition="'$(BuildTargetPlatform)' == 'macos'">
    <TargetFramework Condition="'$(TargetFramework)' == ''">$(MacTargetFramework)</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(BuildTargetPlatform)' == 'windows'">
    <TargetFramework Condition="'$(TargetFramework)' == ''">$(WindowsTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
